export enum EnumPermission {
    PostNovel = 'PostNovel', 
    PostComment = 'PostComment', 
    PostReview = 'PostReview', 
    Report = 'Report', 
    ManagerTag = 'ManagerTag', 
    ManagerCategory = 'ManagerCategory', 
    ManagerUser = 'ManagerUser', 
    ManagerRole = 'ManagerRole', 
    ManagerPublishNovel = 'ManagerPublishNovel', 
    ManagerNovel = 'ManagerNovel', 
    ManagerReport = 'ManagerReport', 
    ManagerUserRole = 'ManagerUserRole', 
    NoComment = 'NoComment', 
    NoPost = 'NoPost', 
    NoReview = 'NoReview', 
    NoReport = 'NoReport', 
    ManagerAuthor = 'ManagerAuthor', 
  }
  